PIDs:
  X:
    kp: 100.0
    kd: 50.0
    ki: 2.0
    minOutput: -150.0
    maxOutput: 150.0
    integratorMin: -15.0
    integratorMax: 15.0
    integratorApproximity: 0.5
  Y:
    kp: -100.0
    kd: -50.0
    ki: -2.0
    minOutput: -150.0
    maxOutput: 150.0
    integratorMin: -15.0
    integratorMax: 15.0
    integratorApproximity: 0.5
  Z:
    kp: 100.0
    kd: 150.0
    ki: 2.0
    minOutput: -250.0
    maxOutput: 150.0
    integratorMin: -25.0
    integratorMax: 25.0
    integratorApproximity: 0.5
  Yaw:
    kp: -200.0
    kd: -20.0
    ki: 0.0
    minOutput: -200.0
    maxOutput: 200.0
    integratorMin: 0.0
    integratorMax: 0.0
    integratorApproximity: 0.5
RC:
  roll:
    min: 1070
    mid: 1488
    max: 1920
  pitch:
    min: 1070
    mid: 1496
    max: 1920
  yaw:
    min: 1070
    mid: 1502
    max: 1920
  thrust:
    min: 1070
    mid: 1340
    max: 1920
ArmThrust: 35
Takeoff:
    thrustStep: 150
    targetHeight: 2.0
    liftThreshold: 0.10
Landing:
    thrustStep: 25
    targetHeight: 0.20
    declineSpeed: 0.40
