PIDs:
  X:
    kp: 40.0
    kd: 20.0
    ki: 2.0
    minOutput: -10.0
    maxOutput: 10.0
    integratorMin: -0.1
    integratorMax: 0.1
  Y:
    kp: -40.0
    kd: -20.0
    ki: -2.0
    minOutput: -10.0
    maxOutput: 10.0
    integratorMin: -0.1
    integratorMax: 0.1
  Z:
    kp: 100.0
    kd: 150.0
    ki: 10.0
    minOutput: -250.0
    maxOutput: 150.0
    integratorMin: -50.0
    integratorMax: 50.0
  Yaw:
    kp: -200.0
    kd: -20.0
    ki: 0.0
    minOutput: -200.0
    maxOutput: 200.0
    integratorMin: 0.0
    integratorMax: 0.0
RC:
  roll:
    min: 1072
    mid: 1496
    max: 1920
  pitch:
    min: 1072
    mid: 1496
    max: 1920
  yaw:
    min: 1072
    mid: 1502
    max: 1920
  thrust:
    min: 1072
    mid: 1400
    max: 1920
    take_off_step: 50
