PIDs:
  X:
    kp: 40.0
    kd: 20.0
    ki: 2.0
    minOutput: -10.0
    maxOutput: 10.0
    integratorMin: -0.1
    integratorMax: 0.1
  Y:
    kp: -40.0
    kd: -20.0
    ki: -2.0
    minOutput: -10.0
    maxOutput: 10.0
    integratorMin: -0.1
    integratorMax: 0.1
  Z:
    kp: 150.0
    kd: 100.0
    ki: 10.0
    minOutput: -250.0
    maxOutput: 250.0
    integratorMin: -200.0
    integratorMax: 200.0
  Yaw:
    kp: -200.0
    kd: -20.0
    ki: 0.0
    minOutput: -200.0
    maxOutput: 200.0
    integratorMin: 0.0
    integratorMax: 0.0
Params:
  RC_minOutput: 1072
  RC_midOutput: 1496
  RC_maxOutput: 1920
  RC_minThrust: 1100
  RC_midRoll: 1495
  RC_midPitch: 1495
  RC_midYaw: 1502
  RC_step: 25
